### ISSUE TITLE
kubed panics when a namespace has been deleted

### ISSUE THREAD

**Issue by caalberts** [kubeops/kubed#479]
We have a kubed deployed in a cluster that sees frequent namespace creation/deletion.

Very often, kubed pod will panic with the following:

```
{
  "jsonPayload": {
    "pid": "1",
    "message": "Observed a panic: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, ListMeta:v1.ListMeta{SelfLink:\"\", ResourceVersion:\"\", Continue:\"\", RemainingItemCount:(*int64)(nil)}, Status:\"Failure\", Message:\"namespaces \\\"my-namespace\\\" not found\", Reason:\"NotFound\", Details:(*v1.StatusDetails)(0xc003508240), Code:404}} (namespaces \"my-namespace\" not found)"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "container_name": "kubed",
      "project_id": "redacted",
      "namespace_name": "redacted",
      "cluster_name": "redacted",
      "pod_name": "kubed-pod"
    }
  },
  "timestamp": "2021-07-01T20:36:22.581105Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/app_kubernetes_io/name": "kubed",
    "compute.googleapis.com/resource_name": "gke-redacted",
    "k8s-pod/pod-template-hash": "79649dc6d8",
    "k8s-pod/app_kubernetes_io/instance": "kubed"
  },
  "logName": "projects/redacted/logs/stderr",
  "sourceLocation": {
    "file": "runtime.go",
    "line": "78"
  },
  "receiveTimestamp": "2021-07-01T20:36:26.023800502Z"
}
```

When this panic happens, the pod would restart or get recreated. Coupled with https://github.com/kubeops/kubed/issues/478, it becomes a problem, because the secrets are not being synced for some time.

**Comment by nilsgstrabo** [comment]
We're experiencing the same issue

Here is the panic trace from the container
```
E0825 14:32:19.533216       1 runtime.go:78] Observed a panic: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"namespaces \"canarycicd-test2-prod\" not found", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc0000ad6e0), Code:404}} (namespaces "canarycicd-test2-prod" not found)
goroutine 243 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19a6820, 0xc006258140)
        /src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x19a6820, 0xc006258140)
        /usr/local/go/src/runtime/panic.go:969 +0x166
k8s.io/apimachinery/pkg/util/runtime.Must(...)
        /src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
github.com/appscode/kubed/pkg/syncer.(*nsSyncer).OnAdd(0xc000572840, 0x1ba0040, 0xc000d8e318)
        /src/pkg/syncer/resourcehandlers.go:152 +0x111
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0x0, 0x0)
        /src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x120
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00065be18, 0x0, 0x0)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000631760)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00065bf60, 0xdf8475800, 0x0, 0x1, 0xc000804060)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0007baa00)
        /src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0001c1480, 0xc000802020)
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: namespaces "canarycicd-test2-prod" not found [recovered]
        panic: namespaces "canarycicd-test2-prod" not found
```

**Comment by absheri** [comment]
We are also seeing the same issue:

```
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19a6820, 0xc00017cc80)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x19a6820, 0xc00017cc80)
	/usr/local/go/src/runtime/panic.go:969 +0x166
k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
github.com/appscode/kubed/pkg/syncer.(*nsSyncer).OnAdd(0xc00000e898, 0x1ba0040, 0xc000903310)
	/src/pkg/syncer/resourcehandlers.go:152 +0x111
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0xc000100000, 0x7f319f5a1108)
	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x120
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000783e18, 0x4, 0xc00058b638)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00058b760)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000783f60, 0xdf8475800, 0x0, 0x1bbc601, 0xc000182720)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0004c5d00)
	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000594ae0, 0xc0002b6310)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: namespaces "e66cdd45-0ec5-41d9-98f2-4f7858b3ef00" not found [recovered]
	panic: namespaces "e66cdd45-0ec5-41d9-98f2-4f7858b3ef00" not found

goroutine 193 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x19a6820, 0xc00017cc80)
	/usr/local/go/src/runtime/panic.go:969 +0x166
k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
github.com/appscode/kubed/pkg/syncer.(*nsSyncer).OnAdd(0xc00000e898, 0x1ba0040, 0xc000903310)
	/src/pkg/syncer/resourcehandlers.go:152 +0x111
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x0, 0xc000100000, 0x7f319f5a1108)
	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x120
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000783e18, 0x4, 0xc00058b638)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00058b760)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000783f60, 0xdf8475800, 0x0, 0x1bbc601, 0xc000182720)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0004c5d00)
	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000594ae0, 0xc0002b6310)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

**Comment by damoon** [comment]
commits to fix this would be https://github.com/turbine-kreuzberg/kubed/commit/dfcce3aa43c02fb30c1592420f57533e91725c5c and https://github.com/turbine-kreuzberg/kubed/commit/d2ae7dec21c2bd0913a52779d4b8eafe3bc5dddb.
would you be interested in a merge request?

**Comment by sathieu** [comment]
@damoon Would you mind creating a PR with your two [above](https://github.com/kubeops/config-syncer/issues/479#issuecomment-963998810) patches?

/CC @tamalsaha
